#!/bin/sh
set -e

case "$1" in
    remove|deconfigure|upgrade)
        if [ -x /usr/lib/duck-keyboard/system-setup.sh ]; then
            /usr/lib/duck-keyboard/system-setup.sh pre-remove /usr/bin/duck-keyboard || true
        fi
        ;;
esac

exit 0
